// Assembly
digraph {
	ATGCA [label="ATGCA 1"]
	TGCAT [label="TGCAT 1"]
	GCATG [label="GCATG 2"]
	CATGC [label="CATGC 2"]
	ATGCG [label="ATGCG 2"]
	TGCGG [label="TGCGG 2"]
	GCGGT [label="GCGGT 2"]
	CGGTA [label="CGGTA 1"]
	GGTAT [label="GGTAT 1"]
	GTATG [label="GTATG 3"]
	TATGT [label="TATGT 1"]
	ATGTA [label="ATGTA 1"]
	TGTAT [label="TGTAT 1"]
	TATGC [label="TATGC 1"]
	ATGCA -> TGCAT [label="ATGCAT 6 1"]
	TGCAT -> GCATG [label="TGCATG 6 1"]
	GCATG -> CATGC [label="GCATGC 6 2"]
	CATGC -> ATGCG [label="CATGCG 6 2"]
	ATGCG -> TGCGG [label="ATGCGG 6 2"]
	TGCGG -> GCGGT [label="TGCGGT 6 2"]
	GCGGT -> CGGTA [label="GCGGTA 6 2"]
	CGGTA -> GGTAT [label="CGGTAT 6 1"]
	GGTAT -> GTATG [label="GGTATG 6 1"]
	GTATG -> TATGC [label="GTATGC 6 1"]
	GTATG -> TATGT [label="GTATGT 6 2"]
	TATGT -> ATGTA [label="TATGTA 6 1"]
	ATGTA -> TGTAT [label="ATGTAT 6 1"]
	TGTAT -> GTATG [label="TGTATG 6 1"]
	TATGC -> ATGCA [label="TATGCA 6 1"]
}
